-- Migration: create section_items table
CREATE TABLE IF NOT EXISTS section_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(64) NOT NULL,
  itemId BIGINT UNSIGNED NOT NULL,
  orderIndex INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_type_order (type, orderIndex)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

