const express = require('express')
const productRouter = express.Router()
const productController = require('./../../controllers/productController')
const customTabbedCategoryController = require('./../../controllers/customTabbedCategoryController')
const authAdminMiddleware = require('./../../middleware/authAdminMiddleware')

// Admin routes (protected)
productRouter.post('/add-product', authAdminMiddleware.verifyAccessToken, productController.addProduct)
productRouter.post('/add-custom-product', authAdminMiddleware.verifyAccessToken, productController.addCustomProduct)
productRouter.post('/edit-product', authAdminMiddleware.verifyAccessToken, productController.editProduct)
productRouter.delete('/delete/:productID', authAdminMiddleware.verifyAccessToken, productController.deleteProduct)
productRouter.post('/bulk-delete', authAdminMiddleware.verifyAccessToken, productController.bulkDeleteProducts)
productRouter.post('/bulk-sale-update', authAdminMiddleware.verifyAccessToken, productController.bulkUpdateSale)
productRouter.post('/bulk-assign-section', authAdminMiddleware.verifyAccessToken, productController.bulkAssignSection)
productRouter.post('/bulk-remove-section', authAdminMiddleware.verifyAccessToken, productController.bulkRemoveSection)
productRouter.get('/count-product', authAdminMiddleware.verifyAccessToken, productController.getProductPageCount)

// Public routes (no auth required)
productRouter.get('/all-products', productController.getPaginatedProducts)
productRouter.get('/details/:productID', productController.getProductDetails)
productRouter.get('/shop', productController.shopList)
productRouter.get('/shop/customtabbed', customTabbedCategoryController.getCustomTabbedCategories)
productRouter.get('/search', productController.searchProducts)

module.exports = productRouter