-- Reusable size charts (image-only)

CREATE TABLE IF NOT EXISTS size_charts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    chartName VARCHAR(255) NOT NULL,
    imgUrl VARCHAR(1024) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

